file_format: "1"
id: gbEnki
name: gbEnki
type: shield
url: https://github.com/aroun/fenki/
requires: [nice_nano_v2]
# exposes: [i2c_oled]
features:
  - keys
siblings:
  - gbEnki_left
  - gbEnki_right
outputs:
  - usb
  - ble
