draw_config:
  key_w: 60.0
  key_h: 56.0
  split_gap: 30.0
  combo_w: 28.0
  combo_h: 26.0
  key_rx: 4.0
  key_ry: 4.0
  dark_mode: false
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: false
  small_pad: 3.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: false
  key_side_pars:
    rel_x: 0
    rel_y: 4
    rel_w: 12
    rel_h: 12
    rx: 4
    ry: 4
  svg_extra_style: '
    :root {
      --hold-color: #04f;
      --combo-color: #fff;
      --held-color: #04f8;
    }
    svg.keymap {font-family: SF Pro Display, SFMono-Regular,Consolas,Liberation Mono,Menlo,monospace;}

    rect.key, rect.combo {
      stroke-width: 0.5;
      stroke: #0004;
    }
    .tap.glyph:has(+.hold.glyph),
    .tap.combo:has(+.hold.combo) {translate: 0 -0.2%;}
    .combo {letter-spacing: -0.1em; dominant-baseline: central;}
    .combo.shifted {dominant-baseline: unset;}
    .layer-activator {translate: 0 -0.1%;}
    .tap.glyph + .hold.glyph {translate: 0 0.05%;}
    text.layer-activator {
      text-decoration-skip-ink: all;
      text-underline-offset: 2px;
      text-decoration-style: dotted;
    }
    path.combo {
      stroke-width: 0.5; stroke: var(--held-color);
    }
    a > .layer-activator,
    .hold.glyph, .hold.combo, .hold.key {
      fill: var(--hold-color); color: var(--hold-color);
    }
    rect.combo, rect.combo-separate {fill: var(--combo-color);}
    rect.held, rect.combo.held {fill: var(--held-color);}
  '
  footer_text: ''
  shrink_wide_legends: 7
  style_layer_activators: true
  glyph_tap_size: 14
  glyph_hold_size: 10
  glyph_shifted_size: 10
  glyphs: {}
parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map:
    "&ru_off": $$mdi:flag-outline$$
    "&ru_on": $$mdi:flag$$
    "&html_tag_open": $$mdi:code-tags$$
    "&html_tag_close": $$mdi:xml$$
    "&par": $$mdi:code-parentheses$$
    "&bkt": $$mdi:code-brackets$$
    "&brc": $$mdi:code-braces$$
    "&soft_off": $$mdi:power-standby$$
    "&bootloader": $$mdi:console$$
    "&studio_unlock": $$mdi:lock-open-variant-outline$$
    "&upd_fw_l": $$mdi:reload-alert$$
    "&upd_fw_r": $$mdi:reload-alert$$
    "&comma_space": ",␣"
    "&comma_space_ru": ",␣"
    "&dot_space": ".␣"
    "&dot_space_ru": ".␣"
    "&check_bat": $$mdi:battery-medium$$
    "&playnp": $$mdi:play-pause$$


  sticky_label: sticky
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  trans_legend:
    t: ◌
    type: trans
  layer_legend_map: {}
  mark_alternate_layer_activators: false
  modifier_fn_map:
    left_ctrl: ⌃
    right_ctrl: ⌃
    left_shift: ⇧
    right_shift: ⇧
    left_alt: ⌥
    right_alt: ⌥
    left_gui: ⌘
    right_gui: ⌘
    keycode_combiner: '{mods}{key}'
    mod_combiner: '{mod_1}{mod_2}'
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: ❖
      left_ctrl+left_alt+left_gui: ◇
  qmk_remove_keycode_prefix:
  - KC_
  qmk_keycode_map:
    XXXXXXX: ''
    'NO': ''
    MINUS: '-'
    MINS: '-'
    EQUAL: '='
    EQL: '='
    LEFT_BRACKET: '['
    LBRC: '['
    RIGHT_BRACKET: ']'
    RBRC: ']'
    BACKSLASH: \
    BSLS: \
    NONUS_HASH: '#'
    NUHS: '#'
    SEMICOLON: ;
    SCLN: ;
    QUOTE: ''''
    QUOT: ''''
    GRAVE: '`'
    GRV: '`'
    COMMA: ','
    COMM: ','
    DOT: .
    SLASH: /
    SLSH: /
    TILDE: '~'
    TILD: '~'
    EXCLAIM: '!'
    EXLM: '!'
    AT: '@'
    HASH: '#'
    DOLLAR: $
    DLR: $
    PERCENT: '%'
    PERC: '%'
    CIRCUMFLEX: ^
    CIRC: ^
    AMPERSAND: '&'
    AMPR: '&'
    ASTR: '*'
    LEFT_PAREN: (
    LPRN: (
    RIGHT_PAREN: )
    RPRN: )
    UNDERSCORE: _
    UNDS: _
    PLUS: +
    LEFT_CURLY_BRACE: '{'
    LCBR: '{'
    RIGHT_CURLY_BRACE: '}'
    RCBR: '}'
    PIPE: '|'
    COLON: ':'
    COLN: ':'
    DOUBLE_QUOTE: '"'
    DQUO: '"'
    DQT: '"'
    LEFT_ANGLE_BRACKET: <
    LABK: <
    LT: <
    RIGHT_ANGLE_BRACKET: '>'
    RABK: '>'
    GT: '>'
    QUESTION: '?'
    QUES: '?'
  zmk_remove_keycode_prefix: []
  zmk_keycode_map:
    LS(N1): '!'
    LS(N2): '@'
    LS(N3): '#'
    LS(N4): '$'
    LS(N5): '%'
    LS(N6): '^'
    LS(N7): '&'
    LS(N8): '*'
    LS(N9): '('
    LS(N0): ')'
    LA(SEMI): '...'
    LS(MINUS): '_'
    LA(LS(MINUS)): '—'

    LG(X): $$mdi:content-cut$$
    LG(C): $$mdi:content-copy$$
    LG(V): $$mdi:content-paste$$
    LA(LC(V)): $$mdi:invoice-text-multiple$$

    RS(RC(TAB)): $$tabler:arrow-autofit-left$$
    RC(TAB): $$tabler:arrow-autofit-right$$

    LG(LEFT): $$tabler:square-chevron-left$$
    LG(RIGHT): $$tabler:square-chevron-right$$
    LC(LEFT): $$mdi:pan-left$$
    LC(RIGHT): $$mdi:pan-right$$

    LC(LA(LCMD)): $$phosphor:regular/diamond$$

    LG(Z): $$mdi:undo-variant$$
    LG(LS(Z)): $$mdi:redo-variant$$
    F13: ✱

    RS(NUMBER_5): ':'
    RS(NUMBER_6): ','
    RS(NUMBER_7): '.'
    RS(NUMBER_8): ';'


    # Symbols
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    AT: "@"
    HASH: "#"
    POUND: "#"
    DOLLAR: $
    DLLR: $
    PERCENT: "%"
    PRCNT: "%"
    CARET: ^
    AMPERSAND: "&"
    AMPS: "&"
    KP_ASTERISK: '*'
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    KP_EQUAL: '='
    EQUAL: "="
    PLUS: +
    MINUS: "-"
    UNDERSCORE: _
    UNDER: _
    KP_DIVIDE: /
    SLASH:
      tap: "/"
      shifted: "?"
    FSLH:
      tap: "/"
      shifted: "?"
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH:
      tap: '\'
      shifted: "|"
    BSLH:
      tap: '\'
      shifted: "|"
    PIPE: "|"
    NON_US_BACKSLASH: \
    PIPE2: "|"
    NON_US_BSLH: "|"
    SEMICOLON:
      tap: ";"
      shifted: ":"
    SEMI:
      tap: ";"
      shifted: ":"
    COLON: ":"
    SINGLE_QUOTE:
      tap: "'"
      shifted: '"'
    SQT:
      tap: "'"
      shifted: '"'

    DOUBLE_QUOTES: '"'
    DQT: '"'
    LA(LC(J)): '=""'
    LS(LA(LC(J))): '«»'
    LESS_THAN: <
    LT: <
    DOT: "."
    COMMA: ","
    GREATER_THAN: ">"
    GT: ">"
    LEFT_BRACKET:
      tap: "["
      shifted: "{"
    LBKT:
      tap: "["
      shifted: "{"
    LEFT_BRACE: "{"
    LBRC: "{"
    RIGHT_BRACKET:
      tap: "]"
      shifted: "}"
    RBKT:
      tap: "]"
      shifted: "}"
    RIGHT_BRACE: "}"
    RBRC: "}"
    GRAVE:
      tap: "`"
      shifted: "~"
    TILDE: "~"
    NON_US_HASH: "#"
    NUHS: "#"
    TILDE2: "~"

    # Numbers
    N1:
      tap: 1
      shifted: "!"
    N2:
      tap: 2
      shifted: "@"
    N3:
      tap: 3
      shifted: "#"
    N4:
      tap: 4
      shifted: "$"
    N5:
      tap: 5
      shifted: "%"
    N6:
      tap: 6
      shifted: "^"
    N7:
      tap: 7
      shifted: "&"
    N8:
      tap: 8
      shifted: "*"
    N9:
      tap: 9
      shifted: "("
    N0:
      tap: 0
      shifted: ")"

    # Modifiers
    LCTRL: $$mdi:apple-keyboard-control$$
    LALT: $$mdi:apple-keyboard-option$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    LCMD: $$mdi:apple-keyboard-command$$
    RCTRL: $$mdi:apple-keyboard-control$$
    RALT: $$mdi:apple-keyboard-option$$
    RSHIFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    RCMD: $$mdi:apple-keyboard-command$$
    LS(LC(LALT)): $$mdi:triangle$$ # Meh

    # Arrows
    UP: $$mdi:arrow-up$$
    DOWN: $$mdi:arrow-down$$
    LEFT: $$mdi:arrow-left$$
    RIGHT: $$mdi:arrow-right$$
    LA(LEFT): $$mdi:arrow-collapse-left$$
    LA(RIGHT): $$mdi:arrow-collapse-right$$
    PG_UP: $$mdi:transfer-up$$
    PG_DN: $$mdi:transfer-down$$
    HOME: $$mdi:arrow-top-left$$
    END: $$mdi:arrow-bottom-right$$

    # Whitespace
    ENTER:
      type: enter
      tap: $$mdi:keyboard-return$$
    ESC: $$mdi:keyboard-esc$$
    TAB: $$mdi:keyboard-tab$$
    LS(TAB): $$mdi:keyboard-tab-reverse$$
    SPACE: $$mdi:keyboard-space$$
    BACKSPACE:
      type: backspace
      tap: $$mdi:backspace$$
    BSPC:
      type: backspace
      tap: $$mdi:backspace$$
    DELETE: $$mdi:backspace-reverse-outline$$
    DEL: $$mdi:backspace-reverse-outline$$

    # Locks
    CAPSLOCK: $$mdi:apple-keyboard-caps$$
    CAPS: $$mdi:apple-keyboard-caps$$

    # Sound
    C_MUTE: $$mdi:volume-off$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-low$$

    # Media
    C_NEXT: $$mdi:skip-next$$
    C_PREV: $$mdi:skip-previous$$
    C_PP: $$mdi:play-pause$$

    # Bluetooth
    BT_CLR: $$mdi:bluetooth-off$$
    BT_SEL: $$mdi:bluetooth-connect$$
    BT_DISC: $$mdi:bluetooth-off$$

    # Settings
    C_BRI_UP: $$mdi:brightness-5$$
    C_BRI_DN: $$mdi:brightness-7$$

    # System
    C_POWER: $$mdi:power-standby$$
    C_AL_LOCK: $$mdi:lock$$
    K_CANCEL: $$mdi:close-box$$

  zmk_combos:
    combo_ru_on:
      align: right
    combo_ru_off:
      align: bottom
    combo_toggle_game:
      align: bottom

  zmk_preamble: '#define KEYMAP_DRAWER'
  zmk_additional_includes: []
