manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: sqdbruh
      url-base: https://github.com/sqdbruh
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: sqdbruh
      revision: main
      import: app/west.yml

      # urob ZMK modules
    - name: zmk-adaptive-key
      remote: urob
      revision: v0.2 # set to same version as zmk above
    - name: zmk-auto-layer
      remote: urob
      revision: v0.2 # set to same version as zmk above
    - name: zmk-leader-key
      remote: urob
      revision: v0.2
    - name: zmk-tri-state
      remote: urob
      revision: v0.2

  self:
    path: config
