manifest:
  defaults:
    remote: urob
    revision: v0.3

  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml

      # urob ZMK modules
    - name: zmk-adaptive-key
      remote: urob
      revision: v0.3 # set to same version as zmk above
    - name: zmk-auto-layer
      remote: urob
      revision: v0.3 # set to same version as zmk above
    - name: zmk-leader-key
      remote: urob
      revision: v0.3
    - name: zmk-tri-state
      remote: urob
      revision: v0.3

  self:
    path: config
